
name: CD

on:
  workflow_run:
    workflows: ["Main CI"]
    types:
      - completed
    
jobs:
   deploy:
    name: Deploy
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        #Download the artifact which was uploaded in the build's job
        uses: dawidd6/action-download-artifact@v2
        with:
           workflow: maven.yml
           name: artifact
      #Deploy the artifact (JAR) into AWS Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          use_existing_version_if_available: false
          application_name: OpenApiGeneratorApplication
          environment_name: Springbootdeploy-env
          version_label: ${{github.SHA}}
          region: us-east-1
          deployment_package: openapi-spring-1.22.1.jar
 
